
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xcb\xfe\x04d\xd4\xe0gsz\rI1\xfb\x11\xaa\x93'
    
_lr_action_items = {'STAR':([0,4,5,6,13,18,19,],[2,2,2,2,21,2,2,]),'NEWPAR':([3,8,9,10,11,12,14,15,16,20,21,22,23,24,],[-5,-2,-13,19,-7,-4,-9,-10,-8,-14,-11,-12,-6,-3,]),'H2':([0,19,],[4,4,]),'H3':([0,19,],[5,5,]),'H1':([0,19,],[6,6,]),'TEXT':([0,2,4,5,6,7,9,11,14,15,16,18,19,20,21,22,],[9,13,9,9,9,17,-13,20,20,20,20,9,9,-14,-11,-12,]),'DSTAR':([0,4,5,6,17,18,19,],[7,7,7,7,22,7,7,]),'CR':([3,8,9,11,12,14,15,16,20,21,22,23,24,],[-5,18,-13,-7,-4,-9,-10,-8,-14,-11,-12,-6,18,]),'$end':([1,3,8,9,10,11,12,14,15,16,20,21,22,23,24,],[0,-5,-2,-13,-1,-7,-4,-9,-10,-8,-14,-11,-12,-6,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'body':([0,],[1,]),'title':([0,19,],[3,3,]),'paragraph':([0,19,],[8,24,]),'statement':([0,],[10,]),'factor':([0,4,5,6,18,19,],[11,14,15,16,11,11,]),'expression':([0,18,19,],[12,23,12,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> body","S'",1,None,None,None),
  ('body -> statement','body',1,'p_body','run.py',52),
  ('statement -> paragraph','statement',1,'p_state_newpar','run.py',56),
  ('statement -> statement NEWPAR paragraph','statement',3,'p_state_newpar','run.py',57),
  ('paragraph -> expression','paragraph',1,'p_state','run.py',64),
  ('paragraph -> title','paragraph',1,'p_state','run.py',65),
  ('paragraph -> paragraph CR expression','paragraph',3,'p_state','run.py',66),
  ('expression -> factor','expression',1,'p_exp_par','run.py',73),
  ('title -> H1 factor','title',2,'p_exp_title','run.py',77),
  ('title -> H2 factor','title',2,'p_exp_title','run.py',78),
  ('title -> H3 factor','title',2,'p_exp_title','run.py',79),
  ('factor -> STAR TEXT STAR','factor',3,'p_factor_em','run.py',88),
  ('factor -> DSTAR TEXT DSTAR','factor',3,'p_factor_stg','run.py',92),
  ('factor -> TEXT','factor',1,'p_factor_text','run.py',96),
  ('factor -> factor TEXT','factor',2,'p_factor_text','run.py',97),
]
